In [1]:
import numpy as np

In [3]:
np.__version__

'1.20.1'

In [4]:
a = np.array([1, 2, 3, 4])

In [6]:
a

array([1, 2, 3, 4])

In [5]:
print(a)

[1 2 3 4]


In [7]:
a.dtype

dtype('int32')

In [8]:
a.ndim

1

In [9]:
a.shape

(4,)

In [12]:
a.itemsize

4

In [13]:
a.ndim, a.shape, a.itemsize

(1, (4,), 4)

In [14]:
a.tolist()

[1, 2, 3, 4]

In [15]:
c = np.array([1, 2, 3])

In [16]:
d = np.array([1, 2, 3])

In [17]:
c is d

False

In [21]:
e = np.asarray(c)

In [22]:
c is e

True

In [23]:
f = c.copy()

In [24]:
c is f

False

In [25]:
import pandas as pd

In [26]:
s = pd.Series([1, 2, 3, 4], index = list('abcd'))

In [27]:
s

a    1
b    2
c    3
d    4
dtype: int64

In [28]:
s.values

array([1, 2, 3, 4], dtype=int64)

In [29]:
s.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [31]:
s.shape, s.size

((4,), 4)

In [36]:
s['a'], s['b']

(1, 2)

In [33]:
s[1]

2

In [37]:
s['a' : 'c']

a    1
b    2
c    3
dtype: int64

In [38]:
s[:]

a    1
b    2
c    3
d    4
dtype: int64

In [39]:
s[:-1]

a    1
b    2
c    3
dtype: int64

In [45]:
df = pd.DataFrame([[1, 2, 3, 4], [5, 6, 7, 8]], index = list('ab'), columns = list('abcd'))

In [46]:
df

a  b  c  d
a  1  2  3  4
b  5  6  7  8